baseurl = ""
metaDataFormat = "yaml"
title = "Frameworks"
theme = "blist"

DefaultContentLanguage = "en"
# DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    # contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Frameworks for data"
      introSubtitle = "Collection of frameworks for data analytics, data storage, modelling, and tracking."
      introPhoto = "/home/undraw_note_list_re_r4u9.svg"
      logo = "/logo/logo.png"
    
    [[languages.en.menu.main]]
        name = "Frameworks"
        url = "frameworks"
        weight = 1

    [[languages.en.menu.main]]
        name = "Categories"
        url = "categories"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "About"
        url = "/about/"
        weight = 4


  # [languages.de]
  #   # contentDir = "content/de" # Deutsch
  #   weight = 2
  #   languageName = "Deutsch"
  #   title = "Blist (mehrsprachig)"
  #   description = "Modernes Blog-Theme für Ihre Hugo-Site."
  #   [languages.de.params]
  #     introTitle = "Eine Hugo-Vorlage für die Erstellung von Listing-Websites"
  #     introSubtitle = "Erstellen von Inserat-Websites mit hugo und Automatisieren der Datenerfassung."
  #     introPhoto = "/home/undraw_note_list_re_r4u9.svg"
  #     logo = "/logo/logo.png"
  #   [[languages.de.menu.main]]
  #       name = "Blog"
  #       url = "blog"
  #       weight = 1

  #   [[languages.de.menu.main]]
  #       name = "Über mich"
  #       url = "page/about/"
  #       weight = 2

  #   [[languages.de.menu.main]]
  #       name = "Tags"
  #       url = "tags"
  #       weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2024 - KausalFlow"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "frameworks"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

[[params.introButton]]
  link = "/frameworks"
  text = "All Frameworks"

[[params.introButton]]
  link = "/submit"
  text = "Submit New"


# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I deal with data."

  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/leima137"
  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://linkedin.com/in/leima137"
  [[params.homepage.social.icons]]
    website = "telegram"
    url = "https://t.me/amneumarkt"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/emptymalei"


[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true


[taxonomies]
    author = "authors"
    category = "categories"
    tag = "tags"

