name: New Framework
description: Suggest a new framework
title: "[New]: "
labels: ["add", "framework", "triage"]
projects: ["emptymalei/10"]
assignees:
  - emptymalei
body:
  - type: input
    id: submitted_by
    attributes:
      label: Submitted by
      description: The user name who submitted this content to be Displayed on the web page
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Name of the tool
      description: Name of the tool to be proposed to add to the website
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summary of the tool
      placeholder: 
    validations:
      required: true
  - type: dropdown
    id: categories
    attributes:
      label: Categories
      multiple: true
      options:
        - workflow
        - ml
        - experiment tracking
        - data catalog
  - type: input
    id: tags
    attributes:
      label: Tags
      description: A list tags, each tag is separated by comma `,`
  - type: checkboxes
    id: terms
    attributes:
      label: CC BY SA 
      description: By submitting this issue, you agree to follow the [CC BY-SA license](https://creativecommons.org/licenses/by-sa/4.0/). 
      options:
        - label: I agree to use CC BY-SA license for my content.
          required: true
